# Generated by Django 3.0.2 on 2020-01-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLearnGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learn_category', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
            ],
            options={
                'verbose_name': 'Группа обучения',
                'verbose_name_plural': 'Группы обучения',
            },
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lic1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lic2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lic3',
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=150, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='categiry_learn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.CategoryLearnGroup', verbose_name='Группа обучения'),
        ),
    ]
