# Generated by Django 3.0.2 on 2020-01-30 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200112_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, default='Пользователь ресурса', max_length=150, verbose_name='О себе'),
        ),
    ]
