# Generated by Django 3.0.2 on 2020-01-31 08:53

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Новый дневник', max_length=150,
                                          verbose_name='Название дневника')),
                ('cat_img', models.ImageField(default='diary_img/diary.jpeg', upload_to='diary_img',
                                              verbose_name='Изображение категории')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                             to=settings.AUTH_USER_MODEL, verbose_name='Автор дневника')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
            },
        ),
        migrations.CreateModel(
            name='DiarySubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='')),
                ('parent',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diary.DiaryCategory',
                                   verbose_name='Дневник')),
            ],
            options={
                'verbose_name': 'Категория дневника',
                'verbose_name_plural': 'Категории дневника',
            },
        ),
        migrations.CreateModel(
            name='DiaryNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title',
                 models.CharField(db_index=True, default='Новая заметка', max_length=150, verbose_name='Заметка')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Текст заметки')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diary.DiarySubCategory',
                                               verbose_name='Категория дневника')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
            },
        ),
    ]
